- name: Reload HAProxy
  service:
    name: haproxy
    state: reloaded

- name: restart systemd
  shell : "systemctl daemon-reload"

- name: restart haprox_exporter
  service:
    name: haproxy_exporter
    state: restarted