- name: install python pip
  apt:
    state: latest
    name: ['docker.io','python3-pip']

- name: Install docker pip
  pip:
    name:
      - docker
      - requests>=2.20.1
- name: Wordpress Docker Container
  docker_container:
      name: wordpress
      image: wordpress:latest
      detach: True
      published_ports:
      - 8080:80
      env: 
        WORDPRESS_DB_USER={{ mysql_db_user }},
        WORDPRESS_DB_HOST=db.zekena.ttu:3306,
        WORDPRESS_DB_PASSWORD={{ mysql_password }},
        WORDPRESS_DB_NAME={{ mysql_db_name }}
      dns_servers:
        - 192.168.56.101
        - 192.168.56.102
      restart_policy: unless-stopped
