- name: install haproxy
  apt:
    state: latest
    name: haproxy

- name: Enable and start HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes

- name: Configure HAProxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: haproxy -c -f %s
  notify:
    Reload HAProxy
