- name: create a folder
  file:
    path: /opt/prometheus
    state: directory
    mode: '0755'
- name: check that file exists
  stat:
    path: /opt/prometheus/prometheus
  register: stat_result

- name: Download prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{pro_version}}/prometheus-{{pro_version}}.linux-amd64.tar.gz
    dest: /opt/prometheus
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: stat_result.stat.exists == False

- name: add prometheus to systemd
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
  notify:
    - restart systemd

- name: start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: copy the prometheus config file
  template:
    src: templates/prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
  notify:
    - restart prometheus
