- name: check that file exists
  stat:
    path: /opt/node_exporter
  register: stat_result
- name: create a folder
  file:
    path: /opt/node_exporter
    state: directory
    mode: '0755'
  when: stat_result.stat.exists == False

- name: Download node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: stat_result.stat.exists == False
- name: add node exporter to systemd
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart systemd
- name: start exporter
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: setup syslog
  template:
    src: 51-telegraf.conf
    dest: /etc/rsyslog.d/51-telegraf.conf
  notify: restart rsyslog