- name: install dependencies
  apt:
    package: ['adduser', 'libfontconfig1']
- name: check inf grafana exists
  stat:
    path: /opt/grafana_6.4.4_amd64.deb
  register: stat_result

- name: download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_6.4.4_amd64.deb
    dest: /opt/grafana_6.4.4_amd64.deb
  when: stat_result.stat.exists == False

- name: install
  apt:
    deb: /opt/grafana_6.4.4_amd64.deb

- name: start grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
