---
- name: Init setup for infra01
  hosts: infra01
  become: yes
  tasks:
    - name: place ssh keys
      authorized_key:
        user: infra01
        key: https://github.com/zekena.keys

    - name: disable sudo pass
      copy:
        dest: /etc/sudoers.d/infra01
        content: "infra01 ALL = NOPASSWD: ALL"
- name: Init for infra02
  hosts: infra02
  become: yes
  tasks:
    - name: place ssh keys
      authorized_key:
        user: infra02
        key: https://github.com/zekena.keys

    - name: disable sudo pass
      copy:
        dest: /etc/sudoers.d/infra02
        content: "infra02 ALL = NOPASSWD: ALL"
