---
- name: backup server configuration
  hosts: infra01
  become: yes
  tasks:

  - name: create backup user
    user:
      name: backup-server
      groups: adm,sudo
      shell: /bin/bash
      home: /home/backup-server
      append: yes
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /home/backup-server/.ssh/id_rsa
      password: ""
      state: present

  - name: copy the public key to the host machine
    fetch:
      src: /home/backup-server/.ssh/id_rsa.pub
      dest: /home/haman/infraCourse/lab6/key/id_rsa(infra01-bakcup).pub
      flat: true

  - name: Create a directory if it does not exist
    file:
      path: /home/backup-server/srv/backup/{{ item }}
      state: directory
      mode: '741'
      owner: backup-server
    with_items:
      - wordpressdb
      - webserver_logs
      - DNS_configs
