---
- name: backup-agent
  hosts: infra01
  become: yes
  tasks:
    - name: create backup user
      user:
        name: backup
        groups: adm,sudo
        shell: /bin/bash
        home: /home/backup
        append: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/backup/.ssh/id_rsa
        password: ""
        state: present
    - name: Create a directory if it does not exist
      file:
        path: /srv/backup
        state: directory
        mode: '0755'
        seuser: backup
    - name: install pip
      apt:
        name: python3-pip
        state: present
    - name: install junos_scp
      pip:
        name: junos_eznc

    - name: copy the public key to the host machine
      fetch:
        src: /home/backup/.ssh/id_rsa.pub
        dest: /home/haman/infraCourse/lab6/id_rsa(infra01-bakcup).pub
        flat: true
