- name: check that file exists
  stat:
    path: /opt/mysqld_exporter
  register: stat_result
- name: create a folder
  file:
    path: /opt/mysqld_exporter
    state: directory
    mode: '0755'
  when: stat_result.stat.exists == False

- name: Download mysqld exporter
  unarchive:
    src: https://github.com/prometheus/mysqld_exporter/releases/download/v0.12.1/mysqld_exporter-0.12.1.linux-amd64.tar.gz
    dest: /opt/mysqld_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: stat_result.stat.exists == False

- name: Copy .my.cnf file
  template:
    src: templates/.my.cnf.j2
    dest: /home/infra02/.my.cnf
# - name: Create mysqld_exporter user
#   command: mysql -u root -e "CREATE USER '{{ mysql_user }}'@'localhost' IDENTIFIED BY '{{ my_pass }}' WITH MAX_USER_CONNECTIONS 3;"
#   ignore_errors: true
#   no_log: true
- name: Make sure mysqld_exporter user has correct privileges on databases
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ my_pass }}"
    priv: '*.*:PROCESS,REPLICATION CLIENT'
    state: present
    host: localhost
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_host: localhost
- name: add mysql exporter to systemd
  template:
    src: templates/mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
  notify: 
    - restart systemd
    - restart mysqld_exporter
- name: start exporter
  service:
    name: mysqld_exporter
    state: started
    enabled: yes